### ISSUE TITLE
Argonne National Laboratory Software Mirror no longer publically accessible.

### ISSUE THREAD

**Issue by joshourisman** [dpiddy/heroku-buildpack-runit#6]
curl requests to download the runit package from http://mirror.anl.gov/pub/ubuntu/pool/universe/r/runit/runit_2.0.0-1ubuntu4_amd64.deb now result in a 403 error, preventing deploys from proceeding.

Details on the change are provided by Argonne by following that URL.

**Comment by joshourisman** [comment]
This also resolves #5, actually.

**Comment by dpiddy** [comment]
Fixed by https://github.com/dpiddy/heroku-buildpack-runit/pull/7.
